version: "3.8"
services:
  webapp:
    build: .
    container_name: visel
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - default
      - public
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 10
      
networks:
  public:
    external: true